### ISSUE TITLE
No Methods Found

### ISSUE THREAD

**Issue by dodekeract** [inch-ci/inch_ci-web#82]
Hi, I can't figure out, why inch doesn't find my getFavicon function ([lib/get.js](https://github.com/dodekeract/favorite/blob/master/lib/get.js?ts=4)).

---
Re: [dodekeract/favorite](https://inch-ci.org/github/dodekeract/favorite)
Inch: [dodekeract/favorite](http://inch-ci.org/github/dodekeract/favorite)

**Comment by rrrene** [comment]
I hang my head in shame for not getting back to you :disappointed: 

Inch does find the function, but is not mentioned in the report because Inch deems it "low priority".

Take a look at [your build history](http://inch-ci.org/github/dodekeract/favorite/branch/master/history). There, click on "Show 1 low priority object ..." to see `getFavicon` (it got an A).

**Comment by dodekeract** [comment]
When I opened this issue there was no `show priority object` link. Also: Why does it think that's low priority? What are the things it's looking for when deciding it? Because that function kind of is all that module does and has to do.

**Comment by rrrene** [comment]
Inch's system of priority is based on the concept of "some things are more important to document than others". In an earlier version of InchJS, one of those rules said that functions start with "get/set" are less important to document than other, since their purpose might be more clear. **That idea was discarded** in the meantime as it does not make as much sense as I first thought.

I resetted your project so it could be re-evaluated with the current InchJS version and [now it shows up correctly](http://inch-ci.org/github/dodekeract/favorite).

**Comment by dodekeract** [comment]
Thanks for resetting it. Glad to hear that has been discarded.
