### ISSUE TITLE
It appears to be inch only picks up files in the root dir

### ISSUE THREAD

**Issue by Gum-Joe** [inch-ci/inch_ci-web#89]
---
Re: [Gum-Joe/Web-OS](http://inch-ci.org/github/Gum-Joe/Web-OS)
In my node-js project,inch failed to evaluate files out the root dir (e.g: it ignored files in my ./libs folder)

**Comment by rrrene** [comment]
You can configure which files inch should parse: https://inch-ci.org/help/config_file_json

    {
      "files": {
        "included": ["libs/"]
      }
    }

Please  note that an alternative to putting the config in an `inch.json` is to put the same hash in your `package.json` under an `inch` key:

    "inch": {
      "files": {
        "included": ["libs/"]
      }
    }

Hope this helps!

**Comment by Gum-Joe** [comment]
Thanks,  thought it would automatically parse all the documents
By the way, does it ignore functions in the form of exports.NameOfFunction()?

**Comment by rrrene** [comment]
Effectively, yes, but not intentional. 

I'm using JSDoc for parsing JavaScript and if JSDoc does not pick it up, then we're out of luck. So while I would very much like to support more common idioms from the JavaScript and especially Node community, I have to "work with what I got" so to speak :wink:

**Comment by Gum-Joe** [comment]
Thankyou, will now close issue
