### ISSUE TITLE
Says module.exports is undocumented when it is documented

### ISSUE THREAD

**Issue by ArtskydJ** [inch-ci/inch_ci-web#94]
inch-ci says module.exports is undocumented when in reality it is documented:
https://github.com/ArtskydJ/tweet-tweet#tweettweetauth

---
Re: [ArtskydJ/tweet-tweet](http://inch-ci.org/github/ArtskydJ/tweet-tweet)

**Comment by rrrene** [comment]
Hi Joseph,

Inch is for [Inline Docs](http://www.yacoset.com/Home/inline-documentation) a.k.a. documentation inside your code in the form of comments. Since you seem to side with [this guy ditching inline docs](http://blog.millermedeiros.com/inline-docs/) I am afraid there is nothing Inch can do for you! :sob:

**Comment by ArtskydJ** [comment]
Sorry, should've seen it was for inline docs.
Thanks for the response!
